### PR TITLE
update: remove apple.com

### PR DESCRIPTION
**Pull request by mikelxk**
Remove apple.com in chinadomain because it's already in nonchinadomain https://github.com/txthinking/bypass/blob/4aed16d1a3f458af6037b2808e897bfdf3a6e793/nonchinadomain.txt#L799-L800
The connection of apple music is really bad when I use bypass mode in brook

### CODE REVIEW

**Comment by txthinking** [comment]
> The connection of apple music is really bad when I use bypass mode in brook

Which is your expectations
1. apple.com should be connected directly
2. apple.com should be connected go through proxy

**Comment by mikelxk** [comment]
> > The connection of apple music is really bad when I use bypass mode in brook
> 
> Which is your expectations
> 
> 1. apple.com should be connected directly
> 2. apple.com should be connected go through proxy

I want to connect to `apple.com` through proxy, the apple music is delivered through `*.music.apple.com` and I believe it's connected directly without proxy now. I'm using the US apple music, that's kind of slow right now.
Maybe a better way to do this is maybe add a rule specifically for `music.apple.com`?
Anyway, there's now `apple.com` existing in both `chinadomain` and `nonchinadomain` and  `chinadomain` has a higher precedence than the other.

**Comment by txthinking** [comment]
> Maybe a better way to do this is maybe add a rule specifically for music.apple.com

Yes, because: Devices using APNs need a **direct connection** to Apple's server. If a device is unable to connect using cellular data, it will attempt to use Wi-Fi if available. If there is a proxy server on the Wi-Fi network, the device will not be able to use APNs, because APNs requires a direct and persistent connection from device to server.

> Anyway, there's now apple.com existing in both chinadomain and nonchinadomain and chinadomain has a higher precedence than the other

`nonchinadomain.txt` was blacklist before, no one is using it now, it is just a backup.

I see, you are using US apple music, I think there will be someone using Chinese apple music, so the solution is creating a new list. 
Because different people need different lists, so I suggest to create a subdirectory `custom`, then you can copy any list from parent directory and edit it.

Example:

```
$ mkdir custom
$ cp chinadomain.txt custom/anynameyouwant.txt
$ vim custom/anynameyouwant.txt # edit it
``` 

then, your will get a list and use it on brook 

```
https://txthinking.github.io/bypass/custom/anynameyouwant.txt
```

**Comment by mikelxk** [comment]
Thanks a lot for your reply!
I'm planning apply my own list on my desktop and remain the original list on my cellphone. 👍

**Pull request closed without merging**
